name: RunTests
on: [push, pull_request]

jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project -e '
            import Pkg
            Pkg.test()'
